---
- name: Init dconf
  ansible.builtin.include_tasks:
    file: _init.yml

- name: Get current panel list
  become: true
  become_user: '{{ customize_user }}'
  community.general.dconf:
    key: /org/mate/panel/general/object-id-list
    state: read
  register: current_panel_list

- name: Set current panel list as default
  ansible.builtin.set_fact:
    panel_list: '{{ current_panel_list.value | from_yaml }}'
  when: current_panel_list.value != None

- name: Add new panel object in dconf
  become: true
  become_user: '{{ customize_user }}'
  ansible.builtin.shell: |
    dbus-launch dconf load /org/mate/panel/objects/ << EOF 
    {{ panel_object.value | launcher_object(name=panel_object.key) }} 
    EOF
  environment:
    DISPLAY: ':0'
  loop: '{{ client_launcher_objects | dict2items }}'
  loop_control:
    loop_var: panel_object
  changed_when: true

- name: Concat original panel list with new launcher objects
  ansible.builtin.set_fact:
    panel_list: '{{ panel_list | union(client_launcher_objects.keys()) }}'

- name: Set new panel list
  become: true
  become_user: '{{ customize_user }}'
  ansible.builtin.shell: |
    dbus-launch dconf load /org/mate/panel/ << EOF 
    [general]
    object-id-list={{ panel_list }} 
    EOF
  environment:
    DISPLAY: ':0'
  when: panel_list is defined
